### ISSUE TITLE
WARNING: Never try to work with this plugin

### ISSUE THREAD

**Issue by vijay-ashok** [lukevers/serverless-offline-msk#2]
I tried to integrate AWS MSK with serverless using this plugin and after trying 3+ days, I got nothing. 
NOTE to author: I highly appreciate creating such plugins but if its not maintained at least give a heads-up saying its not man. Totally frustrated using this plugin

My serverless.yml file
```
EventsProcessor:
  handler: src/handlers/events.handler
  layers:
    - {Ref: PythonRequirementsLambdaLayer}
  timeout: 300
  events:
    - msk: 
        arn: '<arn of AWS MSK>'
        topic: <topic name>
        batchSize: 100
        startingPosition: LATEST
        enabled: true # this will turn it off
```

custom.yml
```
serverless-offline-msk:
  allowAutoTopicCreation: true # If we can create topics in kafka automatically
  brokers: # list of brokers to use for kafka
    - "AWS MSK broker 1"
    - "AWS MSK broker 2"
```
